os: linux
dist: xenial
language: c
compiler:
  - gcc
cache: ccache
addons:
  apt:
    packages:
      - libjpeg-dev
      - libmad0-dev
env:
  global:
    - SRC_DIR="."
    - BUILD_DIR="."
    - CONFIG="--target-list=arm-softmmu --disable-docs --disable-tools --disable-user"
    - TEST_CMD=":"
git:
  # we want to do this ourselves
  submodules: false
before_script:
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - ${SRC_DIR}/configure ${CONFIG} || { cat config.log && exit 1; }
script:
  - make -j3 && ${TEST_CMD}
