dist: xenial
language: c
compiler:
  - gcc
cache: ccache
env:
  global:
    - SRC_DIR="."
    - BUILD_DIR="."
    - CONFIG="--target-list=arm-softmmu --disable-docs --disable-tools --disable-user"
    - TEST_CMD=":"
    - MAKEFLAGS="-j3"
git:
  # we want to do this ourselves
  submodules: false
before_install:
  - git submodule update --init --recursive capstone dtc ui/keycodemapdb
before_script:
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - ${SRC_DIR}/configure ${CONFIG} || { cat config.log && exit 1; }
script:
  - make ${MAKEFLAGS} && ${TEST_CMD}
